export const expressApi = "/api";

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_STORE = 'SET_CURRENT_STORE';
export const SET_STORE_ORDERS = 'SET_STORE_ORDERS';
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER';
export const SET_ITEM_TYPES = 'SET_ITEM_TYPES';
export const SET_TAILOR_LIST = 'SET_TAILOR_LIST';
export const SET_COMPANY_LIST = 'SET_COMPANY_LIST';
export const SET_CUSTOMER_MEASUREMENTS = 'SET_CUSTOMER_MEASUREMENTS';
export const SET_CURRENT_PRINT = 'SET_CURRENT_PRINT';
export const SET_NEW_ORDERS = 'SET_NEW_ORDERS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const ADD_GARMENT_TO_CART = 'ADD_GARMENT_TO_CART';
export const REMOVE_GARMENT_FROM_CART = 'REMOVE_GARMENT_FROM_CART';
export const UPDATE_CART_CUSTOMER_INFO = 'UPDATE_CART_CUSTOMER_INFO';
export const UPDATE_CART_SHIP_TO = 'UPDATE_CART_SHIP_TO';
export const SET_CONFIRMED_NEW_ORDER = 'SET_CONFIRMED_NEW_ORDER';
export const RESET_CART = 'RESET_CART';
export const UPDATE_CART_NOTES = 'UPDATE_CART_NOTES';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const storeTypes = [
  { name: 'Tailor', id: 'tailor' },
  { name: 'Retailer', id: 'retailer'}
];
