import {
  takeUpPantHemImage,
  taperPantLegImage,
  pantsSeatWaistbandTakenInImage,
  shirtSleevesLengthTakenUp,
  shirtSleevesTakenIn,
  shirtHemTakenUp,
  tShirtHemTakenUp,
  shirtShouldersTakenIn,
  shortenSkirt,
  takeInSkirt,
  shortenDress,
  takeInDress,
  shortenFromDressShoulders,
  shortenJacketLength,
  shortenSleeveLength,
  jacketSidesTakenIn,
  jacketSleevesTakenIn,
  shortenTie,
  jeansSeatWaistbandTakenInImage,
  shirtSideSeamsTakenIn,
  takeInJacketShoulders,
} from '../images/how_to_pin';

export default function() {
  return {
    alterations: [
      {
        id: 1,
        garmentId: 1,
        title: 'Shorten Pant Length - Regular Hem',
        price: 15.5,
        howToPin: takeUpPantHemImage,
        type: 'hem',
      },
      {
        id: 2,
        garmentId: 1,
        title: 'Shorten Pant Length - Original Hem',
        price: 24.0,
        howToPin: takeUpPantHemImage,
        type: 'hem',
      },
      //{
      //  id: 3,
      //  garmentId: 1,
      //  title: 'Shorten Pant Length - Blind Stitch Hem',
      //  price: 15.5,
      //  howToPin: takeUpPantHemImage,
      //  type: 'hem',
      //},
      {
        id: 4,
        garmentId: 1,
        title: 'Shorten Pant Length - Cuffed Hem',
        price: 24.0,
        howToPin: takeUpPantHemImage,
        type: 'hem',
      },
      {
        id: 5,
        garmentId: 1,
        title: 'Slim Pants Legs (Taper)',
        price: 24.0,
        howToPin: taperPantLegImage,
        type: 'taper',
      },
      {
        id: 6,
        garmentId: 1,
        title: 'Seat / Waistband Taken In — Pants',
        price: 24.0,
        howToPin: pantsSeatWaistbandTakenInImage,
        type: 'waistband',
      },
      {
        id: 7,
        garmentId: 1,
        title: 'Seat / Waistband Taken In — Jeans',
        price: 50.0,
        howToPin: jeansSeatWaistbandTakenInImage,
        type: 'waistband',
      },
      {
        id: 8,
        garmentId: 2,
        title: 'Shirt Sleeves Length Taken Up — With Cuff',
        price: 25.0,
        howToPin: shirtSleevesLengthTakenUp,
        type: 'sleevesTakenUp',
      },
      {
        id: 9,
        garmentId: 2,
        title: 'Shirt Sleeves Length Taken Up — Without Cuff',
        price: 15.5,
        howToPin: shirtSleevesLengthTakenUp,
        type: 'sleevesTakenUp',
      },
      {
        id: 10,
        garmentId: 2,
        title: 'Shirt Sleeves Taken In',
        price: 24.0,
        howToPin: shirtSleevesTakenIn,
        type: 'sleevesTakenIn',
      },
      {
        id: 11,
        garmentId: 2,
        title: 'Shirt Side Seams Taken In',
        price: 25.0,
        howToPin: shirtSideSeamsTakenIn,
        type: 'shirtSideSeemsTakenIn',
      },
      {
        id: 12,
        garmentId: 2,
        title: 'Shorten Dress Shirt Length',
        price: 24.0,
        howToPin: shirtHemTakenUp,
        type: 'shirtLength',
      },
      {
        id: 13,
        garmentId: 2,
        title: 'Shorten T-Shirt Length',
        price: 15.5,
        howToPin: tShirtHemTakenUp,
        type: 'shirtLength',
      },
      {
        id: 14,
        garmentId: 2,
        title: 'Shirt Shoulders Taken In',
        price: 35.0,
        howToPin: shirtShouldersTakenIn,
        type: 'shirtShoulders',
      },
      {
        id: 15,
        garmentId: 3,
        title: 'Shorten Skirt Length',
        price: 24.0,
        howToPin: shortenSkirt,
        type: 'skirtLength',
      },
      {
        id: 16,
        garmentId: 3,
        title: 'Take In Waist',
        price: 30.0,
        howToPin: takeInSkirt,
        type: 'takeInSkirt',
      },
      {
        id: 17,
        garmentId: 4,
        title: 'Shorten Dress Length',
        price: 24.0,
        howToPin: shortenDress,
        type: 'dressLength',
      },
      {
        id: 18,
        garmentId: 4,
        title: 'Take In Waist',
        price: 30.0,
        howToPin: takeInDress,
        type: 'takeInDressWaist',
      },
      {
        id: 19,
        garmentId: 4,
        title: 'Shorten Dress Shoulder Straps',
        price: 15.0,
        howToPin: shortenFromDressShoulders,
        type: 'dressShoulders',
      },
      {
        id: 20,
        garmentId: 5,
        title: 'Shorten Jacket Length',
        price: 70.0,
        howToPin: shortenJacketLength,
        type: 'jacketLength',
      },
      {
        id: 21,
        garmentId: 5,
        title: 'Shorten Sleeve Length - From Wrist',
        price: 40.0,
        howToPin: shortenSleeveLength,
        type: 'jacketSleeveLength',
      },
      {
        id: 22,
        garmentId: 5,
        title: 'Shorten Sleeve Length - From Shoulder',
        price: 85.0,
        howToPin: shortenSleeveLength,
        type: 'jacketSleeveLength',
      },
      {
        id: 23,
        garmentId: 5,
        title: 'Jacket Sides Taken In',
        price: 50.0,
        howToPin: jacketSidesTakenIn,
        type: 'jacketSides',
      },
      {
        id: 24,
        garmentId: 5,
        title: 'Jacket Sleeves Taken In',
        price: 50.0,
        howToPin: jacketSleevesTakenIn,
        type: 'jacketSleevesTakenIn',
      },
      {
        id: 25,
        garmentId: 5,
        title: 'Take Shoulders In',
        price: 50.0,
        howToPin: takeInJacketShoulders,
        type: 'takeInJacketShoulders',
      },
      {
        id: 26,
        garmentId: 6,
        title: 'Shorten Tie Length',
        price: 25.0,
        howToPin: shortenTie,
        type: 'tie',
      },
      {
        id: 27,
        garmentId: 6,
        title: 'Narrow Tie Width',
        price: 25.0,
        howToPin: shortenTie,
        type: 'tie',
      },
      {
        id: 28,
        garmentId: 6,
        title: 'Shorten and Narrow',
        price: 35.0,
        howToPin: shortenTie,
        type: 'tie',
      },
    ],
  };
}
